### ISSUE TITLE
RippledNotInitializedError: Rippled not initialized

### ISSUE THREAD

**Issue by asielgil88** [WietseWind/docker-rippled#3]
Hi i was able to configure and run the **docker-ripple** when i run, server is running i can see logs and server_info 

docker exec rippled server_info | grep server_state

```
Loading: "/etc/opt/ripple/rippled.cfg"
2019-Jan-11 16:34:58.173321800 HTTPClient:NFO Connecting to 127.0.0.1:5005

         "server_state" : "full",
```

but when i connect ripple-lib to the server using the default config by port 80

im getting 

```
UnhandledPromiseRejectionWarning: RippledNotInitializedError: Rippled not initialized
    at _disconnect.then (/Users/asiel.gil/Workspace/xrp-project/xrp-project-server/parse-server/node_modules/ripple-lib/dist/npm/common/connection.js:162:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7566) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by asielgil88** [comment]
**It's working now** Not sure what's going on i have to wait for few hours of sync, to get a success-full response i tried, this before on an Ubuntu Server instance and it didn't take that long, 

Closing this
